// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-WcHz0mfmxVjs1Pk5FNP1vI2T9rXLi4Q',
    appId: '1:601501456281:web:6255400cd5c42610d7e508',
    messagingSenderId: '601501456281',
    projectId: 'kuveni-app',
    authDomain: 'kuveni-app.firebaseapp.com',
    storageBucket: 'kuveni-app.firebasestorage.app',
    measurementId: 'G-6MMWREZ0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvprL62Qc8u5W-AdBQ_4nIk47GmeHGqwc',
    appId: '1:601501456281:android:7caa6b05891bed60d7e508',
    messagingSenderId: '601501456281',
    projectId: 'kuveni-app',
    storageBucket: 'kuveni-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtNn9n6joc8SRIwXMMggEt4LcrxNvsuVg',
    appId: '1:601501456281:ios:9a58cd26015a9177d7e508',
    messagingSenderId: '601501456281',
    projectId: 'kuveni-app',
    storageBucket: 'kuveni-app.firebasestorage.app',
    iosClientId: '601501456281-m3h2tvu5qsvaofe2vprlg3rehvf9nie0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuveniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtNn9n6joc8SRIwXMMggEt4LcrxNvsuVg',
    appId: '1:601501456281:ios:9a58cd26015a9177d7e508',
    messagingSenderId: '601501456281',
    projectId: 'kuveni-app',
    storageBucket: 'kuveni-app.firebasestorage.app',
    iosClientId: '601501456281-m3h2tvu5qsvaofe2vprlg3rehvf9nie0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuveniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-WcHz0mfmxVjs1Pk5FNP1vI2T9rXLi4Q',
    appId: '1:601501456281:web:1c8969edbf5ac65fd7e508',
    messagingSenderId: '601501456281',
    projectId: 'kuveni-app',
    authDomain: 'kuveni-app.firebaseapp.com',
    storageBucket: 'kuveni-app.firebasestorage.app',
    measurementId: 'G-C8B4WVFFLL',
  );

}